import { SavedSession } from "./types";

export const SEED_SESSION: SavedSession = {
  id: "seed_naresh",
  timestamp: "2026-07-11T23:09:00Z",
  duration: 33,
  fileName: "naresh_speech_sample.wav",
  overallScore: 81,
  clarity: 85,
  fluency: 78,
  pacing: 80,
  stress: 82,
  transcript: "Hi I am Naresh Chandu a full stack developer third year B.Tech computer science student at SRKR Engineering College with CGPA of 8.80 I am I am interested in full stack developer using React JS Next JS Express JS Node JS MongoDB and I am build the projects like QuickBite MovieFlix Flowrevia and developer portfolio",
  feedback: {
    words: [
      { word: "Hi", score: 95, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "I", score: 94, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "am", score: 93, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "Naresh", score: 92, errorType: "none", explanation: "Strong, clear pronunciation of standard Indian name segment." },
      { word: "Chandu", score: 92, errorType: "none", explanation: "Strong, clear pronunciation of standard Indian name segment." },
      { word: "a", score: 95, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "full", score: 96, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "stack", score: 94, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "developer", score: 92, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "third", score: 91, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "year", score: 94, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "B.Tech", score: 88, errorType: "none", explanation: "Good clarity on phonetic acronym transition." },
      { word: "computer", score: 93, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "science", score: 95, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "student", score: 92, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "at", score: 96, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "SRKR", score: 85, errorType: "none", explanation: "Good pronunciation." },
      { word: "Engineering", score: 94, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "College", score: 93, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "with", score: 95, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "CGPA", score: 89, errorType: "none", explanation: "Good pronunciation." },
      { word: "of", score: 95, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "8.80", score: 91, errorType: "none", explanation: "Clear digit delivery." },
      { word: "I", score: 55, errorType: "inserted", phonemes: "aɪ", explanation: "Hesitation repetition detected. Repetition of 'I am' disrupts natural rhythm and flow.", actionableAdvice: "Take a breath and pause instead of repeating the word." },
      { word: "am", score: 55, errorType: "inserted", phonemes: "æm", explanation: "Hesitation repetition detected.", actionableAdvice: "Try to link your words without repeating." },
      { word: "I", score: 94, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "am", score: 94, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "interested", score: 92, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "in", score: 95, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "full", score: 96, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "stack", score: 94, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "developer", score: 92, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "using", score: 93, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "React", score: 91, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "JS", score: 90, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "Next", score: 92, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "JS", score: 90, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "Express", score: 93, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "JS", score: 90, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "Node", score: 92, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "JS", score: 90, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "MongoDB", score: 89, errorType: "none", explanation: "Good pronunciation." },
      { word: "and", score: 95, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "I", score: 94, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "am", score: 93, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "build", score: 48, errorType: "mispronounced", phonemes: "bɪld", explanation: "The final sound /d/ was omitted, making it sound like 'buil'.", actionableAdvice: "Press tongue tip firmly against the roof of the mouth and release with a small burst of air to sound the /d/." },
      { word: "the", score: 95, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "projects", score: 94, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "like", score: 95, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "QuickBite", score: 88, errorType: "none", explanation: "Clear pronunciation of composite term." },
      { word: "MovieFlix", score: 89, errorType: "none", explanation: "Clear pronunciation." },
      { word: "Flowrevia", score: 72, errorType: "mispronounced", phonemes: "floʊ-re-vi-ə", explanation: "Vocal stress was placed on the wrong syllable. Ideal stress is on 're'.", actionableAdvice: "Lengthen the 're' vowel and raise your pitch slightly on this syllable: flow-RE-via." },
      { word: "and", score: 94, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "developer", score: 91, errorType: "none", explanation: "Excellent pronunciation." },
      { word: "portfolio", score: 82, errorType: "mispronounced", phonemes: "pɔːrt-foʊ-li-oʊ", explanation: "The 'o' sound in the second syllable was slightly flat.", actionableAdvice: "Keep your lips rounded as you transition to the second syllable." }
    ],
    generalAdvice: "Clear and intelligible speech with minor areas for articulation and fluency polishing. Focus on linking words smoothly and reducing hesitations.",
    intelligibilityExplanation: "The overall delivery is strong and highly intelligible, but can be improved by releasing final consonants clearly and avoiding repetitive vocal pauses.",
    keyStrengths: [
      "Excellent pronunciation of technical acronyms and stack terminology",
      "Good overall pace and readable cadences"
    ],
    focusAreas: [
      "Release final consonants (e.g., the /d/ in 'build')",
      "Avoid repeating 'I am' when hesitating during a transition"
    ]
  }
};
